### ISSUE TITLE
sometimes it drops out and just doesn't talk to MQTT anymore?

### ISSUE THREAD

**Issue by yaleman** [yaleman/mqttgpio#2]
Process doesn't crash, it just doesn't work.

` 07:56:11 up 6 days, 20:34,  1 user,  load average: 0.10, 0.09, 0.08`

```$ systemctl status mqttgpio.service
● mqttgpio.service - MQTT Home Assistant GPIO Controller
   Loaded: loaded (/opt/mqttgpio/mqttgpio.service; enabled; vendor preset: enabled)
   Active: active (running) since Tue 2019-11-26 11:23:21 AEST; 6 days ago
 Main PID: 851 (python3)
    Tasks: 3 (limit: 2200)
   Memory: 7.9M
   CGroup: /system.slice/mqttgpio.service
           └─851 python3 /opt/mqttgpio/mqttgpio.py```

Restarted the service and it came straight back up.

Maybe need a "am I connected to mqtt" or something check.

**Comment by yaleman** [comment]
Logs for restart, showing how long it'd been up/restart process

```Nov 30 11:39:23 powerpi.housenet.yaleman.org mqttgpio.py[851]: Command to powerpi_2: b'ON'
Nov 30 11:41:22 powerpi.housenet.yaleman.org mqttgpio.py[851]: Command to powerpi_1: b'ON'
Nov 30 11:41:23 powerpi.housenet.yaleman.org mqttgpio.py[851]: Command to powerpi_2: b'ON'
Nov 30 11:43:22 powerpi.housenet.yaleman.org mqttgpio.py[851]: Command to powerpi_1: b'ON'
Nov 30 11:43:23 powerpi.housenet.yaleman.org mqttgpio.py[851]: Command to powerpi_2: b'ON'
Nov 30 11:45:22 powerpi.housenet.yaleman.org mqttgpio.py[851]: Command to powerpi_1: b'ON'
Nov 30 11:45:23 powerpi.housenet.yaleman.org mqttgpio.py[851]: Command to powerpi_2: b'ON'
Nov 30 11:47:22 powerpi.housenet.yaleman.org mqttgpio.py[851]: Command to powerpi_1: b'ON'
-- Logs begin at Tue 2019-11-26 11:17:01 AEST, end at Tue 2019-12-03 07:54:57 AEST. --
Nov 26 11:17:04 powerpi.housenet.yaleman.org systemd[1]: Started MQTT Home Assistant GPIO Controller.
Nov 26 11:17:06 powerpi.housenet.yaleman.org mqttgpio.py[354]: Loaded configuration from: /etc/mqttgpio.conf
Nov 26 11:17:07 powerpi.housenet.yaleman.org mqttgpio.py[354]: Traceback (most recent call last):
Nov 26 11:17:07 powerpi.housenet.yaleman.org mqttgpio.py[354]:   File "/opt/mqttgpio/mqttgpio.py", line 175, in <module>
Nov 26 11:17:07 powerpi.housenet.yaleman.org mqttgpio.py[354]:     client.connect(mqtt_broker, mqtt_port, 60)
Nov 26 11:17:07 powerpi.housenet.yaleman.org mqttgpio.py[354]:   File "/usr/local/lib/python3.7/dist-packages/paho/mqtt/client.py", line 839, in connect
Nov 26 11:17:07 powerpi.housenet.yaleman.org mqttgpio.py[354]:     return self.reconnect()
Nov 26 11:17:07 powerpi.housenet.yaleman.org mqttgpio.py[354]:   File "/usr/local/lib/python3.7/dist-packages/paho/mqtt/client.py", line 962, in reconnect
Nov 26 11:17:07 powerpi.housenet.yaleman.org mqttgpio.py[354]:     sock = socket.create_connection((self._host, self._port), source_address=(self._bind_address, 0))
Nov 26 11:17:07 powerpi.housenet.yaleman.org mqttgpio.py[354]:   File "/usr/lib/python3.7/socket.py", line 707, in create_connection
Nov 26 11:17:07 powerpi.housenet.yaleman.org mqttgpio.py[354]:     for res in getaddrinfo(host, port, 0, SOCK_STREAM):
Nov 26 11:17:07 powerpi.housenet.yaleman.org mqttgpio.py[354]:   File "/usr/lib/python3.7/socket.py", line 748, in getaddrinfo
Nov 26 11:17:07 powerpi.housenet.yaleman.org mqttgpio.py[354]:     for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
Nov 26 11:17:07 powerpi.housenet.yaleman.org mqttgpio.py[354]: socket.gaierror: [Errno -3] Temporary failure in name resolution
Nov 26 11:17:07 powerpi.housenet.yaleman.org systemd[1]: mqttgpio.service: Main process exited, code=exited, status=1/FAILURE
Nov 26 11:17:07 powerpi.housenet.yaleman.org systemd[1]: mqttgpio.service: Failed with result 'exit-code'.
Nov 26 11:23:21 powerpi.housenet.yaleman.org systemd[1]: mqttgpio.service: Service RestartSec=1min expired, scheduling restart.
Nov 26 11:23:21 powerpi.housenet.yaleman.org systemd[1]: mqttgpio.service: Scheduled restart job, restart counter is at 1.
Nov 26 11:23:21 powerpi.housenet.yaleman.org systemd[1]: Stopped MQTT Home Assistant GPIO Controller.
Nov 26 11:23:21 powerpi.housenet.yaleman.org systemd[1]: Started MQTT Home Assistant GPIO Controller.
Nov 26 11:23:21 powerpi.housenet.yaleman.org mqttgpio.py[851]: Loaded configuration from: /etc/mqttgpio.conf
Nov 26 11:23:22 powerpi.housenet.yaleman.org mqttgpio.py[851]: /usr/local/lib/python3.7/dist-packages/gpiozero/devices.py:279: PinFactoryFallback: Falling back from rpigp
Nov 26 11:23:22 powerpi.housenet.yaleman.org mqttgpio.py[851]:   'Falling back from %s: %s' % (name, str(e))))
Nov 26 11:23:22 powerpi.housenet.yaleman.org mqttgpio.py[851]: /usr/local/lib/python3.7/dist-packages/gpiozero/devices.py:279: PinFactoryFallback: Falling back from rpio:
Nov 26 11:23:22 powerpi.housenet.yaleman.org mqttgpio.py[851]:   'Falling back from %s: %s' % (name, str(e))))
Nov 26 11:23:22 powerpi.housenet.yaleman.org mqttgpio.py[851]: Connected with result code 0
Nov 26 11:23:22 powerpi.housenet.yaleman.org mqttgpio.py[851]: Starting the main loop
Nov 26 11:25:11 powerpi.housenet.yaleman.org mqttgpio.py[851]: Command to powerpi_1: b'ON'```
